### ISSUE TITLE
'connection' event triggers after user don't pass verification

### ISSUE THREAD

**Issue by shacharz** [einaros/ws#417]
closing a socket, and then denying it connection if he tries to reconnect in verifyClient options still triggers 'connection' event.

reproduce:
1. client connects to ws server
2. close this client from the server (socket.close)
3. client tried to reconnect to ws server
4. ws server denies the clients connection in the verifyClient options
5. .on('connection') still being triggered
6. client receives 401 on the connection request

**Comment by manuguerra** [comment]
@shacharz I wasn't able to reproduce the issue, can you please provide a sample code where it happens? Thanks!

**Comment by shacharz** [comment]
Hmm, I can't reproduce it again as well (Maybe it was on an old ws version?). 
I'll close and if I'll run into it again with a good reproduction I'll reopen.
