### ISSUE TITLE
How can i retrieve a user cookie on connection?

### ISSUE THREAD

**Issue by r3wt** [einaros/ws#425]
Is it possible? a desirable solution would be to be able to retrieve a session id from the initial upgrade request, then store that session id in the client object. in this way, when i run a broadcasting function, i can send to specific clients by calling `ws.clients[session_id].send()`

**Comment by r3wt** [comment]
found it.
```js
ws.on('connection', function(ws) {
			console.log(ws.upgradeReq.headers.cookie);
});
```

**Comment by rystaf** [comment]
In case anyone else stumbles upon this issue like I did, I think this might be what you're looking for now
```
wss.on('connection', function(ws, req) {
    console.log(req.headers.cookie);
});
```
