### ISSUE TITLE
ws.broadcast messages output undefined to console and the client browser

### ISSUE THREAD

**Issue by r3wt** [einaros/ws#426]
using the following code

```js
"use strict";
var http = require('http'),
WebSocketServer = require('ws').Server,
port = 9001
;
web_server = http.createServer(function(req, res) {
	res.writeHead(200);
}).listen(port, function() {
	console.log('websocket server listening on port %d\n',port);
});
var ws = new WebSocketServer({
	server : web_server,
	clientTracking: true,
});
ws.broadcast = function broadcast(data) {
	for(var i in this.clients){
		if(this.clients[i].readyState !== this.clients[0].OPEN){
			console.error('Client state is %s',this.clients[i].readyState);
		}else{
			this.clients[i].send(data,{binary:false,masked:false},function ack(error){
				if(error !== null){
					console.log(error+"\r\n");
				}
			});	
		}
	}
}
ws.random_price = function(){
	return Math.floor(Math.random()* Math.random() * 50000);
};
ws.random_market = function(){
	return 'MKT/BTC'+Math.floor(Math.random()*50);
};

ws.mkt_test_msg = function(){
	var msg = {'event':'mkt_price','price':ws.random_price(),'pair':ws.random_market()};
	return msg || {};
}
console.log(JSON.stringify(ws.mkt_test_msg())); //outputs expected json object
setInterval(function(){
	if(ws.clients.length > 0){
		ws.broadcast(JSON.stringify(ws.mkt_test_msg()));//outputs undefined!
	}
},50);
```

**Comment by 3rd-Eden** [comment]
I highly doubt that this is a bug in the library as all our test pass and write the correct data as expected. Your code on the other hand contains a lot of bugs. For example you loop over an array using `for in` instead of `for`, `while` or `forEach` etc.

**Comment by r3wt** [comment]
@3rd-Eden the `for/in` loop you reference was copied from your examples in the README of this repo. the loop works as the client receives data but its just "undefined". same thing is output to console.

**Comment by r3wt** [comment]
![image](https://cloud.githubusercontent.com/assets/4483325/5600408/de9647cc-929e-11e4-912e-54bc3251a34a.png)

**Comment by r3wt** [comment]
proof the error is originating inside of the send function. i'm going to remove the cluster lib and forking and see if that helps. if it doesn't solve it, is there an email address i can mail you the code and instructions to reproduce?
```js
setInterval(function(){
	if(ws.clients.length > 0){
		var msg = ws.mkt_test_msg();
		console.log(msg);
		ws.broadcast(JSON.stringify(msg));
	}
},50);
```
![image](https://cloud.githubusercontent.com/assets/4483325/5600488/7a39ac9a-92a0-11e4-9389-bf34af827527.png)

**Comment by r3wt** [comment]
@3rd-Eden https://github.com/einaros/ws/blob/master/README.md#server-sending-broadcast-data

**Comment by 3rd-Eden** [comment]
@r3wt I'm not the author of this library, i'm merely a simple contributor ;-). I haven't touched/read through the documentation and readme in ages. I just look at the code and see that clients is an array not an object: https://github.com/einaros/ws/blob/master/lib/WebSocketServer.js#L86

As for the undefined it makes sense as you check if error is not `null` in the send callback. That's true, because it's `undefined` as there is no error, causing you to log `undefined`

**Comment by r3wt** [comment]
@3rd-Eden  That error check was also in the documentation. I'm a first time Nodester.  so perhaps you can change the error handling best practices to read

```js

if(typeof error !== 'undefined'){
	console.log(error+"\r\n");
}

```

also, fwiw i decided to log the event in the browser console and its straight up undefined. i obviously have no reason to come to github and lie right? 

![image](https://cloud.githubusercontent.com/assets/4483325/5600658/bf614a4a-92a4-11e4-9431-dd5cb7b02742.png)

**Comment by r3wt** [comment]
Edit, i found the problem!

attempting to use jquery to wrap the event is resulting in some loss of the event's properties. the problem was clientside and not serverside.
