### ISSUE TITLE
How to check the outgoing buffer size?

### ISSUE THREAD

**Issue by natrixnatrix89** [einaros/ws#428]
I'd like to implement something like volatile messages.
So if I have heavy amount of data, and the network can't handle that, the outgoing buffer may pile up.
I'd like to terminate the connection when reaching a certain limit for the buffer.
NodeJS sockets have a property `bufferSize` http://nodejs.org/api/net.html#net_socket_buffersize.
However when I launch a ws server and inspect a single ws client connection, I notice that it actually has multiple sockets, that have the attribute `bufferSize`
```javascript
ws._socket;
ws._ultron.ee;
ws.upgradeReq.socket;
ws.upgradeReq.connection;
ws.upgradeReq.client;
ws._sender._socket;
```
Which of these is the socket for outgoing data, that I could use to determine if there isn't a problem with congestion of the messages, and that isn't piling up?

**Comment by 3rd-Eden** [comment]
https://github.com/einaros/ws/blob/master/lib/WebSocket.js#L360

aka, `ws.bufferedAmount`

**Comment by natrixnatrix89** [comment]
Thanks! I had noticed it, but wasn't sure what it's for.
