### ISSUE TITLE
Auto re-connect support

### ISSUE THREAD

**Issue by adityapatadia** [einaros/ws#431]
Can we add support for auto-reconnect when connection is dropped?

**Comment by 3rd-Eden** [comment]
That is out of the scope of this project. If you want such features I would suggest looking at things like [Primus](https://github.com/primus/primus) or [reconnecting-websocket](https://github.com/joewalnes/reconnecting-websocket)

**Comment by adityapatadia** [comment]
Ok. Thanks.

**Comment by adityapatadia** [comment]
What about adding at least a ```connect``` method for client so that we can re-connect when connection is dropped. I use it in nodejs and reconnection is desired there.

**Comment by 3rd-Eden** [comment]
Just create a new instance?

**Comment by adityapatadia** [comment]
What happens to old event listeners then? Do I need to bind them again with ```.on```?

**Comment by 3rd-Eden** [comment]
Of course, as it's new instance.

**Comment by adityapatadia** [comment]
Ok, cool. Thanks for quick support.

**Comment by tomalex0** [comment]
@adityapatadia ,  do you have snippet to share the way you don auto re connect.

Or did you used primus or reconnecting-websocket modues

**Comment by adityapatadia** [comment]
I used simple setTimeout based logic at that time. When connection dropped, I re-connected it again after some delay. But somehow it was not very reliable so I switched to socket.io for my project.

**Comment by Bomper** [comment]
Reconnecting a client has already been discussed in #163.

**Comment by slidenerd** [comment]
Primus is super bloated. you have already emitted an 'unexpected-response' event which further calls an abortHandshake method where you are emitting an 'error' event , what you could do is have an extra option inside ws options in the constructor that tries to establish the initial connection again when 'error' or 'unexpected-response' events are emitted and also a setInterval that checks for 'WebSocket.readyState === OPEN'
