### ISSUE TITLE
Using cluster for multiple processes

### ISSUE THREAD

**Issue by mkamioner** [einaros/ws#438]
Hi,

I would like to increase the maximum amount of connections on one machine by using the cluster library in NodeJS. When I spin up 7 children (I have 8 cores) and try to connect hundreds of connections, the connections are waited toward the first process of the 7. Is there a way to get the division of the connections to be more even?

Thanks!
Mike

**Comment by 3rd-Eden** [comment]
This is flaw of cluster, not of ws. Solution is to stop using cluster for load balancing and use a proper load balancer like HAProxy or nginx instead.

**Comment by DavidSouther** [comment]
Nb Node 0.12 and iojs both promise improvements in the native cluster algorithms.
